# the dot infront of circleci . are system files and are automatically hidden by default users, jobs what we want our server to do,its creating our image where we can run our tests, circle ci is going to use this container for our enviorment for our tests. 
version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command