# the dot infront of circleci . are system files and are automatically hidden by default users, jobs what we want our server to do,its creating our image where we can run our tests, circle ci is going to use this container for our enviorment for our tests.
version: 2
jobs:
  #these are diffrent containers
  bobby:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:8.9 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "npm installing" # run the `echo` command
  sally: # use the docker executor type; machine and macos executors are also supported
    docker:
      - image: circleci/node:8.9 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "testing stuff" # run the `echo` command
workflows:
  version: 2
  bobby_sally:
    jobs:
      - bobby
      - sally
